default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: phase2_exam_development

test:
  <<: *default
  database: phase2_exam_test

production:
  <<: *default
  database: phase2_exam_production
  username: phase2_exam
  password: <%= ENV['PHASE2_EXAM_DATABASE_PASSWORD'] %>
